# From https://github.com/marketplace/actions/deploy-to-neocities
name: Deploy to neocities

# only run on changes to master
on:
  push:
    branches:
      - main

env:
  FORCE_COLOR: 1
  node_version: 20

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    # Set up any tools and build steps here
    # This example uses a Node.js toolchain to build a site
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
          node-version: ${{ env.node_version }}
    - run: npm ci
    - run: npm run build
    # When the dist_dir is ready, deploy it to neocities
    - name: Deploy to neocities
      uses: bcomnes/deploy-to-neocities@v1
      with:
        api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
        cleanup: true
        dist_dir: public
        protected_files: '/img/*'
